// src/content/enhance/config.js
// Shared constants for the Enhance underline feature.

export const ENH_ROOT_FLAG = "__VIB_ENH_ROOT__";
export const ENHANCE_IDS = Object.freeze({
  underlineHost: "__vib_enh_underline_host__",
  modalHost: "__vib_enh_modal_host__",
  modalId: "vib-suggest",
});

export const Z_INDEX_BASE = 2147483600;

export const COMPOSER_SELECTORS = Object.freeze([
  "textarea",
  'input[type="text"]',
  'input[type="search"]',
  'input[type="email"]',
  'input[type="url"]',
  '[contenteditable="true"]',
  '[role="textbox"]',
  ".ProseMirror",
  ".ql-editor",
  ".monaco-editor",
  '[data-slate-editor="true"]',
]);

export const ENH_CFG = Object.freeze({
  ENABLED: true,
  ANIMATIONS_ENABLED: false,
  HOVER_DELAY_MS: 300,
  ADAPTIVE_DEBOUNCE_MS: 160,
  COOLDOWN_MS: 0,
  EPHEMERAL: { FULL: 4000, HALF: 8000, QUARTER: 12_000 },
  MAX_CLUSTERS: 3,
  COLORS: {
    underline: "#a0a2da",
    underlineLight: "#8e90d3",
    underlineDark: "#b3b5e3",
    modalBorder: "rgba(160,162,218,0.25)",
    modalBgLight: "rgba(255,255,255,0.96)",
    modalBgDark: "rgba(26,26,28,0.96)",
    header: { light: "#9ca3af", dark: "#c7c9d3" },
    item: "#a0a2da",
  },
  INTENT: {
    verbs: [
      "write",
      "draft",
      "generate",
      "summarize",
      "analyze",
      "compare",
      "refactor",
      "design",
      "outline",
      "plan",
      "explain",
      "translate",
      "debug",
      "propose",
      "brainstorm",
      "research",
      "improve",
    ],
    wh: ["who", "what", "when", "where", "why", "how"],
    polite: [
      "can you",
      "could you",
      "would you",
      "please",
      "help me",
      "walk me through",
    ],
  },
  REQUEST_PREFIXES: [
    "i need",
    "i need you to",
    "i want",
    "i'd like",
    "i would like",
    "i am looking for",
    "i'm looking for",
    "i would love",
    "i'd love",
    "i gotta",
    "i have to",
    "we need",
    "we want",
    "please provide",
    "please create",
    "please help",
    "please give",
    "please show",
  ],
  COMMAND_PHRASES: [
    "give me",
    "send me",
    "put together",
    "come up with",
    "walk through",
    "build me",
    "create",
    "craft",
    "spin up",
    "draft up",
    "lay out",
    "put down",
  ],
  THIRD_PARTY_PREFIXES: [
    "my boss wants",
    "my boss needs",
    "my boss asked",
    "my manager wants",
    "my manager asked",
    "my manager needs",
    "my team needs",
    "our team needs",
    "our team wants",
    "leadership wants",
    "leadership asked",
    "client wants",
    "client needs",
    "client asked",
    "stakeholders need",
    "stakeholders want",
    "stakeholder asked",
  ],
  HELPER_VERBS: ["need", "needs", "needed", "want", "wants", "wanted", "ask", "asked", "asking", "require", "requires", "required"],
  PRONOUN_PREFIXES: [
    "i",
    "i'm",
    "i am",
    "we",
    "we're",
    "we are",
    "my boss",
    "my manager",
    "my client",
    "our client",
    "my team",
    "our team",
    "the team",
    "leadership",
    "stakeholders",
  ],
  DAMPEN: [
    "weather",
    "temperature",
    "what time",
    "coin flip",
    "roll a dice",
    "roll dice",
    "ping",
  ],
  LENGTH_THRESHOLD_WORDS: 10,
});

export const LOG_PREFIX = "[VG][Enhance]";
